name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      id: version
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${increment}"

        
    - name: Login to Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.ouputs.version }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login success"
        echo "La nueva version va a ser $NEW_VERSION"


    # - name: Build Docker Image
    #   env:
    #     DOCKER_USER: ${{ secrets.DOCKER_USER }}
    #   run: |
    #    docker build -t $DOCKER_USER/docker-graphql:0.0.2 .
    #    docker build -t $DOCKER_USER/docker-graphql:latest .

    # - name: Push Docker Image
    #   env:
    #     DOCKER_USER: ${{ secrets.DOCKER_USER }}
    #   run: |
    #    docker push $DOCKER_USER/docker-graphql:0.0.2
    #    docker push $DOCKER_USER/docker-graphql:latest
       
   
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
